services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped

    network_mode: host

    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro

    environment:
      - TZ=Europe/Berlin

    privileged: true